###
GET http://localhost:8080/

###
POST http://localhost:8080/
Content-Type: application/json

{
    "nome": "Jeronimo",
    "cpf": "123456",
    "rg": "12315515",
    "sexo": "Masculino",
    "data_nasc": "2005-04-23"
}

###
PUT http://localhost:8080/1
Content-Type: application/json

{
    "nome": "Bruno",
    "cpf": "1234567",
    "rg": "2005-04-23",
    "sexo": "Masculino",
    "data_nasc": "2005-04-23"
}